sudo: required

language: c

compiler: gcc

services: docker

before_install:
    - docker build -t BIOSCat/ubuntu .
    - docker run -v $PWD:/root/engine BIOSCat/ubuntu /bin/sh -c "cd /root/engine; make test"
