sudo: required

language: c

compiler: gcc

services: docker

before_install:
    - docker build -t bioscat/ubuntu .

script:
    - docker run -v $PWD:/root/engine bioscat/ubuntu /bin/sh -c "cd /root/engine; make check"
